version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./healthcare-backend
    container_name: healthcare-backend
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: rootpassword
      DB_NAME: mydb
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./healthcare-frontend
    container_name: healthcare-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mysql_data:
